# Generated by Django 4.2.15 on 2024-09-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
